### ISSUE TITLE
Error: InvalidBucketName: The specified bucket is not valid.

### ISSUE THREAD

**Issue by benseitz** [zodern/mup-aws-beanstalk#14]
The deployment fails super fast with:
```
$ mup deploy
=> Setting up
{ InvalidBucketName: The specified bucket is not valid.
    at Request.extractError (/node_modules/aws-sdk/lib/services/s3.js:577:35)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'The specified bucket is not valid.',
  code: 'InvalidBucketName',
  region: null,
  time: 2018-01-24T04:07:31.780Z,
  requestId: 'XXX',
  extendedRequestId: 'XXXXXXXXXXX',
  cfId: undefined,
  statusCode: 400,
  retryable: false,
  retryDelay: 36.13655784318708 }
```

I folled the instructions and set the IAM permissions

**Comment by benseitz** [comment]
Found it! The app name can't start with an uppercase letter.

**Comment by zodern** [comment]
Version 0.4.0 is now available with this fixed.
