### ISSUE TITLE
Deploy Error: InvalidLocationConstraint: The specified location-constraint is not valid

### ISSUE THREAD

**Issue by cormip** [zodern/mup-aws-beanstalk#175]
Using `mup v1.5.10` successfully deploys apps to AWS and DigitalOcean without problems.

However, I'm attempting to use plugin `mup-aws-beanstalk v0.8.0` but I'm receiving an error during deployment:

```bash
D:\myapp\.deploy-dev-aws-beanstalk>mup.cmd deploy
  mup:plugin-loader loading plugin mup-aws-beanstalk +0ms
  mup:plugin-loader plugin installed locally with mup +4ms
  mup:updates checking for updates +0ms
  mup:updates Packages:  [
  {
    name: 'mup',
    path: 'C:\\Users\\me\\AppData\\Roaming\\nvm\\v14.21.2\\node_modules\\mup\\package.json'
  },
  {
    name: 'mup-aws-beanstalk',
    path: 'C:\\Users\\me\\AppData\\Roaming\\nvm\\v14.21.2\\node_modules\\mup-aws-beanstalk\\index.js'
  }
] +0ms
  mup:updates retrieving tags for mup +2ms
  mup:updates retrieving tags for mup-aws-beanstalk +16ms
  mup:api Running command default.deploy +0ms
  mup:module:default exec => mup deploy +0ms
  mup:api Running command beanstalk.deploy +9ms
  mup:api Running command beanstalk.setup +0ms
=> Setting up
(node:25356) NOTE: We are formalizing our plans to enter AWS SDK for JavaScript (v2) into maintenance mode in 2023.

Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
  mup:updates finished update check for mup-aws-beanstalk +354ms
  mup:updates finished update check for mup +3ms
  mup:api _commandErrorHandler +474ms
  mup:api _commandErrorHandler: nodemiral error +1ms
InvalidLocationConstraint: The specified location-constraint is not valid
    at Request.extractError (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\services\s3.js:711:35)
    at Request.callListeners (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\sequential_executor.js:106:20)
    at Request.emit (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\request.js:38:9)
    at Request.<anonymous> (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\request.js:688:12)
    at Request.callListeners (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\sequential_executor.js:116:18)
    at Request.emit (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\sequential_executor.js:78:10)
    at Request.emit (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\request.js:686:14)
    at Request.transition (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\state_machine.js:26:10
    at Request.<anonymous> (C:\Users\me\AppData\Roaming\nvm\v14.21.2\node_modules\mup-aws-beanstalk\node_modules\aws-sdk\lib\request.js:38:9)

D:\myapp\.deploy-dev-aws-beanstalk>
```
Any thoughts on how to get past this?

**Comment by cormip** [comment]
OK, this error was caused by specifying `app.region: 'us-east-1'`.

Apparently there's a [weird bug in the AWS SDK createBucket that requires you to NOT to specify a locationContraint if creating a bucket in 'us-east-1'](https://stackoverflow.com/questions/51912072/invalidlocationconstraint-error-while-creating-s3-bucket-when-the-used-command-i).

Once I removed the `app.region` parameter, the deploy script proceeded without error. I did not close this issue, because this should be documented in the docs as a warning.

**Comment by paulincai** [comment]
Hi @cormip, did you open a PR for this to be documented in the docs?

**Comment by derwaldgeist** [comment]
Just ran into the same problem. Removing "us-east-1" helped.
