### ISSUE TITLE
Failing to build

### ISSUE THREAD

**Issue by out0mana** [zodern/mup-aws-beanstalk#21]
npm-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node',
1 verbose cli   '/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm',
1 verbose cli   '--production',
1 verbose cli   'install' ]
2 info using npm@3.10.10
3 info using node@v6.11.5
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly install normalizeTree
8 silly loadCurrentTree Finishing
9 silly loadIdealTree Starting
10 silly install loadIdealTree
11 silly cloneCurrentTree Starting
12 silly install cloneCurrentTreeToIdealTree
13 silly cloneCurrentTree Finishing
14 silly loadShrinkwrap Starting
15 silly install loadShrinkwrap
16 silly loadShrinkwrap Finishing
17 silly loadAllDepsIntoIdealTree Starting
18 silly install loadAllDepsIntoIdealTree
19 silly loadAllDepsIntoIdealTree Finishing
20 silly loadIdealTree Finishing
21 silly currentTree mup-es-web@2.0.0
22 silly idealTree mup-es-web@2.0.0
23 silly generateActionsToTake Starting
24 silly install generateActionsToTake
25 silly generateActionsToTake Finishing
26 silly diffTrees action count 0
27 silly decomposeActions action count 0
28 silly runTopLevelLifecycles Starting
29 silly install runPreinstallTopLevelLifecycles
30 silly preinstall mup-es-web@2.0.0 /tmp/deployment/application/mup-es-web-978bc7a0
31 info lifecycle mup-es-web@2.0.0~preinstall: mup-es-web@2.0.0
32 verbose lifecycle mup-es-web@2.0.0~preinstall: unsafe-perm in lifecycle true
33 verbose lifecycle mup-es-web@2.0.0~preinstall: PATH: /opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/lib/node_modules/npm/bin/node-gyp-bin:/tmp/deployment/application/node_modules/.bin:/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin:/opt/elasticbeanstalk/lib/ruby/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
34 verbose lifecycle mup-es-web@2.0.0~preinstall: CWD: /tmp/deployment/application
35 silly lifecycle mup-es-web@2.0.0~preinstall: Args: [ '-c', 'cd programs/server && npm install' ]
36 silly lifecycle mup-es-web@2.0.0~preinstall: Returned: code: 1  signal: null
37 info lifecycle mup-es-web@2.0.0~preinstall: Failed to exec preinstall script
38 silly rollbackFailedOptional Starting
39 silly rollbackFailedOptional Finishing
40 silly runTopLevelLifecycles Finishing
41 silly install printInstalled
42 warn mup-es-web@2.0.0 No repository field.
43 verbose If you need help, you may report this error at:
43 verbose     <https://github.com/npm/npm/issues>
44 warn mup-es-web@2.0.0 No license field.
45 verbose If you need help, you may report this error at:
45 verbose     <https://github.com/npm/npm/issues>
46 verbose stack Error: mup-es-web@2.0.0 preinstall: `cd programs/server && npm install`
46 verbose stack Exit status 1
46 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
46 verbose stack     at emitTwo (events.js:106:13)
46 verbose stack     at EventEmitter.emit (events.js:191:7)
46 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:40:14)
46 verbose stack     at emitTwo (events.js:106:13)
46 verbose stack     at ChildProcess.emit (events.js:191:7)
46 verbose stack     at maybeClose (internal/child_process.js:920:16)
46 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:230:5)
47 verbose pkgid mup-es-web@2.0.0
48 verbose cwd /tmp/deployment/application
49 error Linux 4.9.76-3.78.amzn1.x86_64
50 error argv "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm" "--production" "install"
51 error node v6.11.5
52 error npm  v3.10.10
53 error code ELIFECYCLE
54 error mup-es-web@2.0.0 preinstall: `cd programs/server && npm install`
54 error Exit status 1
55 error Failed at the mup-es-web@2.0.0 preinstall script 'cd programs/server && npm install'.
55 error Make sure you have the latest version of node.js and npm installed.
55 error If you do, this is most likely a problem with the mup-es-web package,
55 error not with npm itself.
55 error Tell the author that this fails on your system:
55 error     cd programs/server && npm install
55 error You can get information on how to open an issue for this project with:
55 error     npm bugs mup-es-web
55 error Or if that isn't available, you can get their info via:
55 error     npm owner ls mup-es-web
55 error There is likely additional logging output above.
56 verbose exit [ 1, true ]
```

So apparently it fails on npm install. I'm having the same exact issues as this guy (https://forums.meteor.com/t/update-delivered-fundraiser-would-you-help-finance-a-plugin-that-would-allow-mup-meteor-up-to-deploy-aws/40057/34)

**Comment by out0mana** [comment]
ELB Health log:
```

  |   | i-0f82277fee7d27d08 | Severe | 2 hours | 6 | - | - | - | - | - | - | - | - | - | - | 0.00 | 0.00 | 0.1 | 0.0 | 99.9 | 0.0
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
Application deployment failed at 2018-02-12T00:04:31Z with exit status 1 and error: Hook /opt/elasticbeanstalk/hooks/appdeploy/pre/50npm.sh failed.+ /opt/elasticbeanstalk/containerfiles/ebnode.py --action npm-install> mup-es-web@1.0.0 preinstall /tmp/deployment/application> cd programs/server && npm install> fibers@1.0.15 install /tmp/deployment/application/programs/server/node_modules/fibers> node build.js \|\| nodejs build.js`linux-x64-48` exists; testingBinary is fine; exiting> meteor-dev-bundle@0.0.0 install /tmp/deployment/application/programs/server> node npm-rebuild.js> bcrypt@1.0.3 install /tmp/deployment/application/programs/server/npm/node_modules/bcrypt> node-pre-gyp install --fallback-to-build[bcrypt] Success: "/tmp/deployment/application/programs/server/npm/node_modules/bcrypt/lib/binding/bcrypt_lib.node" is installed via remotenpm ERR! Linux 4.9.76-3.78.amzn1.x86_64npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm" "rebuild" "--update-binary"npm ERR! node v6.11.5npm ERR! npm v3.10.10npm ERR! path /tmp/deployment/application/programs/server/npm/node_modules/sshpk/bin\sshpk-convnpm ERR! code ENOENTnpm ERR! errno -2npm ERR! syscall chmodnpm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/deployment/application/programs/server/npm/node_modules/sshpk/bin\sshpk-conv'npm ERR! enoent ENOENT: no such file or directory, chmod '/tmp/deployment/application/programs/server/npm/node_modules/sshpk/bin\sshpk-conv'npm ERR! enoent This is most likely not a problem with npm itselfnpm ERR! enoent and is related to npm not being able to find a file.npm ERR! enoent npm ERR! Please include the following file with any support request:npm ERR! /tmp/deployment/application/programs/server/npm/npm-debug.lognpm WARN meteor-dev-bundle@0.0.0 No descriptionnpm WARN meteor-dev-bundle@0.0.0 No repository field.npm WARN meteor-dev-bundle@0.0.0 No license field.npm ERR! Linux 4.9.76-3.78.amzn1.x86_64npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm" "install"npm ERR! node v6.11.5npm ERR! npm v3.10.10npm ERR! code ELIFECYCLEnpm ERR! meteor-dev-bundle@0.0.0 install: `node npm-rebuild.js`npm ERR! Exit status 254npm ERR! npm ERR! Failed at the meteor-dev-bundle@0.0.0 install script 'node npm-rebuild.js'.npm ERR! Make sure you have the latest version of node.js and npm installed.npm ERR! If you do, this is most likely a problem with the meteor-dev-bundle package,npm ERR! not with npm itself.npm ERR! Tell the author that this fails on your system:npm ERR! node npm-rebuild.jsnpm ERR! You can get information on how to open an issue for this project with:npm ERR! npm bugs meteor-dev-bundlenpm ERR! Or if that isn't available, you can get their info via:npm ERR! npm owner ls meteor-dev-bundlenpm ERR! There is likely additional logging output above.npm ERR! Please include the following file with any support request:npm ERR! /tmp/deployment/application/programs/server/npm-debug.lognpm WARN mup-es-web@1.0.0 No repository field.npm WARN mup-es-web@1.0.0 No license field.npm ERR! Linux 4.9.76-3.78.amzn1.x86_64npm ERR! argv "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm" "--production" "install"npm ERR! node v6.11.5npm ERR! npm v3.10.10npm ERR! code ELIFECYCLEnpm ERR! mup-es-web@1.0.0 preinstall: `cd programs/server && npm install`npm ERR! Exit status 1npm ERR! npm ERR! Failed at the mup-es-web@1.0.0 preinstall script 'cd programs/server && npm install'.npm ERR! Make sure you have the latest version of node.js and npm installed.npm ERR! If you do, this is most likely a problem with the mup-es-web package,npm ERR! not with npm itself.npm ERR! Tell the author that this fails on your system:npm ERR! cd programs/server && npm installnpm ERR! You can get information on how to open an issue for this project with:npm ERR! npm bugs mup-es-webnpm ERR! Or if that isn't available, you can get their info via:npm ERR! npm owner ls mup-es-webnpm ERR! There is likely additional logging output above.npm WARN Local package.json exists, but node_modules missing, did you mean to install?npm ERR! Please include the following file with any support request:npm ERR! /tmp/deployment/application/npm-debug.logRunning npm install: /opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npmSetting npm config jobs to 1npm config jobs set to 1Running npm with --production flagFailed to run npm install. Snapshot logs for more details.Traceback (most recent call last):File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 695, in <module>main()File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 677, in mainnode_version_manager.run_npm_install(options.app_path)File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 136, in run_npm_installself.npm_install(bin_path, self.config_manager.get_container_config('app_staging_dir'))File "/opt/elasticbeanstalk/containerfiles/ebnode.py", line 180, in npm_installraise esubprocess.CalledProcessError: Command '['/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/npm', '--production', 'install']' returned non-zero exit status 1.
```

**Comment by zodern** [comment]
The problem is `enoent ENOENT: no such file or directory, chmod '/tmp/deployment/application/programs/server/npm/node_modules/sshpk/bin\sshpk-conv'`.

What version of Meteor are you using?

There is a plugin that tries to fix it: https://github.com/zodern/mup-fix-bin-paths

**Comment by out0mana** [comment]
Im using Meteor 1.6.1. I saw your plugin but I don't think it supports this meteor version

**Comment by zodern** [comment]
Meteor 1.6.1 is using a version of npm with the bug fixed that is causing the problem with sshpk. Try deleting `node_modules` and running `meteor npm install`.
