### ISSUE TITLE
app.volumes is an unkown property

### ISSUE THREAD

**Issue by out0mana** [zodern/mup-aws-beanstalk#26]
I am trying to have persistent files stored using Meteor-Files.
If i run my mup.js with no volumes i get this error:
```

> mup-es-web@6.0.0 start /var/app/current
> bash ./start.sh

Node version
v8.9.3
Npm version

┌──────────────────────────────────────────────────┐
│             npm update check failed              │
│       Try running with sudo or get access        │
│       to the local update config store via       │
│ sudo chown -R $USER:$(id -gn $USER) /tmp/.config │
└──────────────────────────────────────────────────┘
5.5.1
=> Starting health check server
=> Starting App

meteor://💻app/packages/ostrio_files.js:414
        throw new Meteor.Error(401, `[FilesCollection.${self.collectionName}] Path "${this.storagePath({})}" is not writable! ${error}`);
        ^
Error: [FilesCollection.Files] Path "/FC_Files" is not writable! Error: EACCES: permission denied, mkdir '/FC_Files' [401]
    at FilesCollection.fs.mkdirs.error (packages/ostrio:files/server.js:271:15)
    at xfs.stat (/var/app/current/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/fs-extra/lib/mkdirs/mkdirs.js:55:43)
    at /var/app/current/programs/server/npm/node_modules/meteor/ostrio_files/node_modules/graceful-fs/polyfills.js:284:29
    at FSReqWrap.oncomplete (fs.js:152:21)
```

but if i try to use volumes in mup.js I get this error:
```
$ mup deploy --settings=settings.json

   ┌─────────────────────────────────────┐
   │                                     │
   │   update available 1.3.7 => 1.4.3   │
   │     To update, run npm i -g mup     │
   │                                     │
   └─────────────────────────────────────┘

loaded config from C:\Users\Admin\Desktop\DASLab\ES-Web\.deploy\mup.js

1 Validation Error
  - "app.volumes" is an unknown property

Read the docs and view example configs at
    http://meteor-up.com/docs

=> Setting up
=> Ensuring IAM Roles and Instance Profiles are setup
Building App Bundle Locally
```
On the meteor-up page they say use meteor:{volumes:{}} but this extensions uses a different way.
Any help would be appreciated

**Comment by zodern** [comment]
Could you please explain your use case for persistent files?

**Comment by out0mana** [comment]
I am using the [Meteor-Files](https://github.com/VeliovGroup/Meteor-Files) package to store files locally. They are backed up to S3 as soon as they are uploaded
