### ISSUE TITLE
Object.getOwnPropertyDescriptors is not a function

### ISSUE THREAD

**Issue by raphaelarias** [zodern/mup-aws-beanstalk#28]
I have an enviroment, where one instance out of 2 is always unhealthy. I was checking the logs on papertrail, and I can see these errors. Would you know what it is?

`
uncaughtException: Object.getOwnPropertyDescriptors is not a function { date: 'Tue Mar 20 2018 11:03:39 GMT+0000 (UTC)', process:  { pid: 26752, uid: 496, gid: 494, cwd: '/var/app/current/programs/server', execPath: '/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node', version: 'v6.11.5', argv:  [ '/opt/elasticbeanstalk/node-install/node-v6.11.5-linux-x64/bin/node', '/var/app/current/main.js', 'program.json' ], memoryUsage:  { rss: 149106688, heapTotal: 117346304, heapUsed: 86553560, external: 25784627 } }, os:  { loadavg: [ 0.91259765625, 0.98486328125, 0.99462890625 ], uptime: 240140 }, trace:  [ { column: 12, file: 'packages/mongo/collection.js', function: 'insert', line: 435, method: null, native: false }, { column: 19, file: 'packages/aldeed:collection2-core/collection2.js', function: 'Mongo.Collection.(anonymous function) [as insert]', line: 205, method: '(anonymous function) [as insert]', native: false }, { column: 20, file: 'packages/autoupdate.js', function: 'updateVersions', line: 125, method: null, native: false }, { column: 3, file: 'packages/autoupdate.js', function: null, line: 189, method: null, native: false }, { column: 28, file: '/var/app/current/programs/server/profile.js', function: 'Function.time', line: 309, method: 'time', native: false }, { column: 13, file: '/var/app/current/programs/server/boot.js', function: null, line: 423, method: null, native: false }, { column: 5, file: '/var/app/current/programs/server/boot.js', function: null, line: 464, method: null, native: false }, { column: 12, file: '/var/app/current/programs/server/profile.js', function: 'Function.run', line: 510, method: 'run', native: false }, { column: 11, file: '/var/app/current/programs/server/boot.js', function: null, line: 462, method: null, native: false } ], stack:  [ 'TypeError: Object.getOwnPropertyDescriptors is not a function', '    at insert (packages/mongo/collection.js:435:12)', '    at Mongo.Collection.(anonymous function) [as insert] (packages/aldeed:collection2-core/collection2.js:205:19)', '    at updateVersions (packages/autoupdate.js:125:20)', '    at packages/autoupdate.js:189:3', '    at Function.time (/var/app/current/programs/server/profile.js:309:28)', '    at /var/app/current/programs/server/boot.js:423:13', '    at /var/app/current/programs/server/boot.js:464:5', '    at Function.run (/var/app/current/programs/server/profile.js:510:12)', '    at /var/app/current/programs/server/boot.js:462:11' ] } 
`

**Comment by raphaelarias** [comment]
I'm not using the beta version but, could be related?

https://github.com/meteor/meteor/issues/9470

**Comment by zodern** [comment]
What version of `mup-aws-beanstalk` and Meteor are you using?

**Comment by raphaelarias** [comment]
Meteor: `METEOR@1.6.0.1`
Mup: 1.4.3
Mup AWS Beanstalk: 0.5.1

**Comment by raphaelarias** [comment]
The weird is that one instance was fine. How can we help fix this "bug"? I know you may have other things to do so. Is there anything we can do or contribute (even financially)?

**Comment by zodern** [comment]
It is probably using the wrong node version.  In the aws console, go to the beanstalk app, click logs, and request the full logs. In the zip file you download, go to `var/log/nodejs`. If there is a rotated folder, uncompress the `.gz` file and open it, otherwise open `nodejs.log`.

At the top of the file, please copy the text before `=> Starting App` and share it here.

**Comment by raphaelarias** [comment]
Yep, tried now making sure i double-checked the node version. One instance is ok, the other is Severe.

The one that is not healthy:
`
-------------------------------------
/var/log/nodejs/nodejs.log
-------------------------------------
> mup-prod-educationlink-for-providers@4.0.0 start /var/app/current
> bash ./start.sh

Node version
v8.9.3
Npm version

â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
â”‚             npm update check failed              â”‚
â”‚       Try running with sudo or get access        â”‚
â”‚       to the local update config store via       â”‚
â”‚ sudo chown -R $USER:$(id -gn $USER) /tmp/.config â”‚
â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜
5.5.1
=> Starting health check server
=> Starting App
Kadira: completed instrumenting the app

> mup-prod-educationlink-for-providers@4.0.0 start /var/app/current
> bash ./start.sh

Node version
v8.9.3
Npm version

â”Œâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”
â”‚             npm update check failed              â”‚
â”‚       Try running with sudo or get access        â”‚
â”‚       to the local update config store via       â”‚
â”‚ sudo chown -R $USER:$(id -gn $USER) /tmp/.config â”‚
â””â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”˜
5.5.1
=> Starting health check server
=> Starting App
Kadira: completed instrumenting the app



-------------------------------------
/var/log/nginx/error.log
-------------------------------------
2018/03/28 23:01:40 [warn] 4443#0: duplicate MIME type "text/html" in /etc/nginx/conf.d/proxy.conf:68
2018/03/28 23:08:02 [warn] 6235#0: duplicate MIME type "text/html" in /etc/nginx/conf.d/proxy.conf:68



-------------------------------------
/var/log/eb-activity.log
-------------------------------------
[2018-03-28T23:07:55.424Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/01stop_xray.sh] : Starting activity...
[2018-03-28T23:07:55.542Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/01stop_xray.sh] : Completed activity. Result:
  Executing: if ( initctl status xray | grep start ); then initctl stop xray; fi
  
[2018-03-28T23:07:55.542Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/02start_xray.sh] : Starting activity...
[2018-03-28T23:07:55.653Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/02start_xray.sh] : Completed activity.
[2018-03-28T23:07:55.653Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/10stop.sh] : Starting activity...
[2018-03-28T23:07:59.191Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/10stop.sh] : Completed activity. Result:
  + /opt/elasticbeanstalk/containerfiles/ebnode.py --action stop-all
  nodejs stop/waiting
  nginx stop/waiting
  status: Unknown job: httpd
  status: Unknown job: httpd
  Job already stopped. Not stopping again.
  Job already stopped. Not stopping again.
  Did not find to find status of init job. Assuming stopped.
  Did not find to find status of init job. Assuming stopped.
[2018-03-28T23:07:59.192Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/20clean.sh] : Starting activity...
[2018-03-28T23:07:59.731Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/20clean.sh] : Completed activity. Result:
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_base_dir
  + EB_APP_BASE_DIR=/var/app
  + rm -rf /var/app
[2018-03-28T23:07:59.731Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/30app_deploy.sh] : Starting activity...
[2018-03-28T23:08:00.266Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/30app_deploy.sh] : Completed activity. Result:
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_base_dir
  + EB_APP_BASE_DIR=/var/app
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_staging_dir
  + EB_APP_STAGING_DIR=/tmp/deployment/application
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_deploy_dir
  + EB_APP_DEPLOY_DIR=/var/app/current
  ++ /opt/elasticbeanstalk/bin/get-config container -k app_user
  + EB_APP_USER=nodejs
  + mkdir /var/app
  + mv /tmp/deployment/application /var/app/current
  + chown -R nodejs:nodejs /var/app/current
[2018-03-28T23:08:00.266Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/40config_deploy.sh] : Starting activity...
[2018-03-28T23:08:00.378Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/40config_deploy.sh] : Completed activity. Result:
  ++ /opt/elasticbeanstalk/bin/get-config container -k config_staging_dir
  + EB_CONFIG_STAGING_DIR=/tmp/deployment/config
  ++ ls /tmp/deployment/config
  + for i in '$(ls $EB_CONFIG_STAGING_DIR)'
  ++ sed -e 's/#/\//g'
  ++ echo '#etc#init#nginx.conf'
  + FILE_NAME=/etc/init/nginx.conf
  + /bin/cp /tmp/deployment/config/#etc#init#nginx.conf /etc/init/nginx.conf
  + for i in '$(ls $EB_CONFIG_STAGING_DIR)'
  ++ sed -e 's/#/\//g'
  ++ echo '#etc#init#nodejs.conf'
  + FILE_NAME=/etc/init/nodejs.conf
  + /bin/cp /tmp/deployment/config/#etc#init#nodejs.conf /etc/init/nodejs.conf
  + for i in '$(ls $EB_CONFIG_STAGING_DIR)'
  ++ sed -e 's/#/\//g'
  ++ echo '#etc#nginx#nginx.conf'
  + FILE_NAME=/etc/nginx/nginx.conf
  + /bin/cp /tmp/deployment/config/#etc#nginx#nginx.conf /etc/nginx/nginx.conf
[2018-03-28T23:08:00.378Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/50start.sh] : Starting activity...
[2018-03-28T23:08:02.015Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/50start.sh] : Completed activity. Result:
  + /opt/elasticbeanstalk/containerfiles/ebnode.py --action start-all
  nodejs start/running, process 6221
  nginx start/running, process 6235
[2018-03-28T23:08:02.015Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/60monitor_pids.sh] : Starting activity...
[2018-03-28T23:08:02.600Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/60monitor_pids.sh] : Completed activity. Result:
  + '[' -d /etc/healthd ']'
  ++ /opt/elasticbeanstalk/bin/get-config optionsettings --namespace aws:elasticbeanstalk:container:nodejs --option-name ProxyServer
  + PROXY_SERVER=nginx
  + case "$PROXY_SERVER" in
  + /opt/elasticbeanstalk/bin/healthd-track-pidfile --proxy nginx
  + /opt/elasticbeanstalk/bin/healthd-track-pidfile --name application --location /var/run/nodejs.pid
[2018-03-28T23:08:02.600Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/70restart_healthd.sh] : Starting activity...
[2018-03-28T23:08:02.830Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook/70restart_healthd.sh] : Completed activity. Result:
  + '[' -d /etc/healthd ']'
  ++ /opt/elasticbeanstalk/bin/get-config optionsettings --namespace aws:elasticbeanstalk:container:nodejs --option-name ProxyServer
  + PROXY_SERVER=nginx
  + '[' -f /var/elasticbeanstalk/healthd/current_proxy_server ']'
  ++ cat /var/elasticbeanstalk/healthd/current_proxy_server
  + CURRENT_PROXY_SERVER=nginx
  + '[' nginx '!=' nginx ']'
  + echo nginx
[2018-03-28T23:08:02.830Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployEnactHook] : Completed activity. Result:
  Successfully execute hooks in directory /opt/elasticbeanstalk/hooks/appdeploy/enact.
[2018-03-28T23:08:02.830Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployPostHook] : Starting activity...
[2018-03-28T23:08:02.830Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1/AppDeployPostHook] : Completed activity. Result:
  Successfully execute hooks in directory /opt/elasticbeanstalk/hooks/appdeploy/post.
[2018-03-28T23:08:02.830Z] INFO  [4774]  - [Application update 4@2/AppDeployStage1] : Completed activity. Result:
  Application version switch - Command CMD-AppDeploy stage 1 completed
[2018-03-28T23:08:02.831Z] INFO  [4774]  - [Application update 4@2/AddonsAfter] : Starting activity...
[2018-03-28T23:08:02.831Z] INFO  [4774]  - [Application update 4@2/AddonsAfter/ConfigLogRotation] : Starting activity...
[2018-03-28T23:08:02.831Z] INFO  [4774]  - [Application update 4@2/AddonsAfter/ConfigLogRotation/10-config.sh] : Starting activity...
[2018-03-28T23:08:03.049Z] INFO  [4774]  - [Application update 4@2/AddonsAfter/ConfigLogRotation/10-config.sh] : Completed activity. Result:
  Disabled forced hourly log rotation.
[2018-03-28T23:08:03.049Z] INFO  [4774]  - [Application update 4@2/AddonsAfter/ConfigLogRotation] : Completed activity. Result:
  Successfully execute hooks in directory /opt/elasticbeanstalk/addons/logpublish/hooks/config.
[2018-03-28T23:08:03.049Z] INFO  [4774]  - [Application update 4@2/AddonsAfter] : Completed activity.
[2018-03-28T23:08:03.049Z] INFO  [4774]  - [Application update 4@2] : Completed activity. Result:
  Application update - Command CMD-AppDeploy succeeded
[2018-03-29T03:31:49.787Z] INFO  [14609] - [CMD-TailLogs] : Starting activity...
[2018-03-29T03:31:49.787Z] INFO  [14609] - [CMD-TailLogs/AddonsBefore] : Starting activity...
[2018-03-29T03:31:49.787Z] INFO  [14609] - [CMD-TailLogs/AddonsBefore] : Completed activity.
[2018-03-29T03:31:49.787Z] INFO  [14609] - [CMD-TailLogs/TailLogs] : Starting activity...
[2018-03-29T03:31:49.787Z] INFO  [14609] - [CMD-TailLogs/TailLogs/TailLogs] : Starting activity...
`

**Comment by raphaelarias** [comment]
@zodern would you know what is happening? If we pay could we prioritise this issue?

**Comment by zodern** [comment]
25% of the servers, rounded up, are replaced during each deploy. I am looking into if there could be a problem with reusing a server.

**Comment by zodern** [comment]
> I am looking into if there could be a problem with reusing a server.

It seems to be working correctly.

There are at least two possible causes for this error:
1) The server is using an older version of Node that doesn't have `getOwnPropertyDescriptors`. According to the logs you showed me, the app is being run with node 8, which supports `getOwnPropertyDescriptors`. Do the logs for either instance show the error, or is it only shown in paper trail?
2) `Object.getOwnPropertyDescriptors` is being overridden. If that was happening, then the app would most likely be crashing on both servers instead of one.

One thing you could try is rebuilding the environment. On the console, click on actions > rebuild environment. Your app will be down for a few minutes while that happens though.

**Comment by raphaelarias** [comment]
Sorry the delay on getting back to you.

I'll deploy again and I'll try to rebuild. But so far I tried to terminate the instance, and deploying it again from scratch.

The logs I showed you above was only be shown on Papertrail. Which is interesting, I guess.

Let me try deploying once more and rebuilding the environment just in case.

Do you believe could be related to https://github.com/meteor/meteor/issues/9470?

**Comment by zodern** [comment]
This should be fixed in 0.7: #142
