### ISSUE TITLE
Invalid Node Value

### ISSUE THREAD

**Issue by PolybitSol** [zodern/mup-aws-beanstalk#6]
Hey,

Excited this plugin is finally out! In the documentation it notes:

```
This plugin supports meteor 1.2 or newer. It will automatically use the correct Node and npm version.
```

However, upon configuring and running ```mup deploy``` I receive the following error:

```
{ ConfigurationValidationException: Configuration validation exception: Invalid option value: '8.4.0' (Namespace: 'aws:elasticbeanstalk:container:nodejs', OptionName: 'NodeVersion'): Value is not one of the allowed values: [4.8.5, 4.8.7, 5.12.0, 6.11.5, 6.12.2, 7.10.1, 8.8.1, 8.9.3]
    at Request.extractError (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/protocol/query.js:47:29)
    at Request.callListeners (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/sequential_executor.js:115:18)
    at Request.emit (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/home/dev/Projects/myapp/src/node_modules/aws-sdk/lib/request.js:38:9)
  message: 'Configuration validation exception: Invalid option value: \'8.4.0\' (Namespace: \'aws:elasticbeanstalk:container:nodejs\', OptionName: \'NodeVersion\'): Value is not one of the allowed values: [4.8.5, 4.8.7, 5.12.0, 6.11.5, 6.12.2, 7.10.1, 8.8.1, 8.9.3]',
  code: 'ConfigurationValidationException',
  time: 2018-01-04T23:49:53.919Z,
  requestId: '6a45c73b-fafa-4e00-a610-c6b870f608ff',
  statusCode: 400,
  retryable: false,
  retryDelay: 88.99876860180925 }
```

My ```mup.js``` is below:

```
module.exports = {
    app: {
        // Tells mup that the AWS Beanstalk plugin will manage the app
        type: 'aws-beanstalk',
        name: 'myapp',
        path: '../',
        env: {
            ROOT_URL: 'http://mydomain.com',
            MONGO_URL: 'mongodb://main:...',
            MONGO_OPLOG_URL: 'mongodb:...',
            MAIL_URL: 'smtp://...'
        },
        auth: {
            id: '...',
            secret: '...'
        },
        minInstances: 1,
        maxInstances: 5,
        instanceType: 't2.micro',
        sslDomains: ['mydomain.com', 'www.mydomain.com'],
        forceSSL: true,
        region: 'eu-west-2',
    },
    plugins: ['mup-aws-beanstalk']
};
```
 
Other information:

```Meteor Version: 1.6```

**Comment by PolybitSol** [comment]
I've updated to Meteor version 1.6.01, and running ```Meteor node --version``` gives the result ```8.9.3``` which is in the allowable values, but for some reason ```mup deploy``` is changing this to ```8.4.0```.

**Comment by zodern** [comment]
I am working on a fix.

There actually are two node versions installed on the servers.
The first one is installed by Beanstalk, and it isn't used. It is the one causing this error.
The second one this plugin [installs using nvm](https://github.com/zodern/mup-aws-beanstalk/blob/master/src/assets/node.yaml#L18), and it is used by your app and has the correct version.

**Comment by zodern** [comment]
Version 0.2.3 has the fix.
