### ISSUE TITLE
Error while uploading bundle - UnknownEndpoint

### ISSUE THREAD

**Issue by cmoses8626** [zodern/mup-aws-beanstalk#65]
After running mup deploy, I get the following error. Note I removed my app name in the URL in the error message. I'm setup a digital certificate using Let's Encrypt instead of using AWS Certificate Manager. Might this be related?

```
=> Uploading bundle
  Uploaded 3%
  Uploaded 6%
  Uploaded 9%
UnknownEndpoint: Inaccessible host: `mup-<MY-APP-NAME>.s3.amazonaws.com'. This service may not be available in the `us-east-1' region.
    at Request.ENOTFOUND_ERROR (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/event_listeners.js:481:46)
    at Request.callListeners (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/request.js:683:14)
    at ClientRequest.error (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/event_listeners.js:320:22)
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/mup-aws-beanstalk/node_modules/aws-sdk/lib/http/node.js:93:19)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at TLSSocket.socketErrorListener (_http_client.js:391:9)
    at TLSSocket.emit (events.js:182:13)
    at TLSSocket.EventEmitter.emit (domain.js:442:20)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by zodern** [comment]
I encountered this today when my laptop got disconnected from the internet. It should retry the upload when this error occurs.
