### ISSUE TITLE
Environment health has transitioned from Severe to Degraded.

### ISSUE THREAD

**Issue by raphaelarias** [zodern/mup-aws-beanstalk#9]
Hello. Congrats for the great work.

I was testing it and in our first attempts we got stuck in (we've aborted the two times): 

```
  => Setting up
=> Ensuring IAM Roles and Instance Profiles are setup
Building App Bundle Locally
=> Archiving Bundle
  10% Archived
  20% Archived
  30% Archived
  40% Archived
  50% Archived
  60% Archived
  70% Archived
  80% Archived
  90% Archived
  100% Archived
=> Uploading bundle
  Uploaded 9%
  Uploaded 19%
  Uploaded 28%
  Uploaded 38%
  Uploaded 47%
  Uploaded 57%
  Uploaded 66%
  Uploaded 76%
  Uploaded 85%
  Uploaded 95%
  Uploaded 100%
  Finishing upload. This could take a couple minutes
=> Creating Version
=> Configuring Beanstalk Environment
=> Deploying new version
=> Waiting for Beanstalk Environment to finish updating
    Env Event: Environment health has transitioned from Warning to Severe. 100.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on all instances. ELB health is failing or not available for all instances.
  Env Event: Rolling with Additional Batch deployment policy enabled. Launching  a new batch of 1 additional instance(s).
  Env Event: Added instance [i-023e5bb56de69c---] to your environment.
  Env Event: Batch 1: 1 EC2 instance(s) [i-023e5bb56de69c---] launched. Deploying application version '4'.
  Env Event: Environment health has transitioned from Severe to Degraded. 100.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on 1 out of 2 instances. Application update in progress on 1 instance. 0 out of 2 instances completed (running for 3 minutes). ELB health is failing or not available for 1 out of 2 instances.
  Env Event: Environment health has transitioned from Degraded to Severe. 100.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on 1 out of 2 instances. Application update in progress on 1 instance. 0 out of 2 instances completed (running for 4 minutes). ELB health is failing or not available for 1 out of 2 instances.
  Env Event: Retrieving logs prior to instance(s) termination. Logs will be available for an hour in the environment management console and at elasticbeanstalk-us-east-1-892415841---/resources/environments/logs/bundle/e-e6xybseikf.
  Env Event: During an aborted deployment, some instances may have deployed the new application version. To ensure all instances are running the same version, re-deploy the appropriate application version.
  Env Event: Failed to deploy application.
  Env Event: Instance id(s) 'i-023e5bb56de69c---' did not pass health check after command execution. Aborting the operation.
  Env Event: [Instance: i-023e5bb56de69c---] Successfully finished bundling 18 log(s)
  Env Event: Excess instance(s) terminated.
  Env Event: Terminating excess instance(s): [i-023e5bb56de69c---].
App is running at --------.us-east-1.elasticbeanstalk.com
=> Finding old versions
=> Removing old versions
=> Checking Certificate Status
TypeError: Cannot read property 'length' of undefined
    at _callee13$ (/usr/local/lib/node_modules/mup-aws-beanstalk/lib/command-handlers.js:894:75)
    at tryCatch (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/mup/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/mup-aws-beanstalk/lib/command-handlers.js:995:191)
    at /usr/local/lib/node_modules/mup-aws-beanstalk/lib/command-handlers.js:995:361
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
```

Would you know what is happening? I believe that the second problem (length of undefined) is because we've set up the certificate ourselves.

```
// mup.js

module.exports = {
  app: {
    type: 'aws-beanstalk',
    name: '',
    path: '../',
    env: {
      MONGO_URL: "",
      MONGO_OPLOG_URL: "",
      MAIL_URL: "",
      ROOT_URL: "",
    },
    auth: {
      id: '',
      secret: '',
    },

    instanceType: 't2.small',
    region: 'us-east-1',
    minInstances: 1,
    maxInstances: 2,

    sslDomains: [''],
    forceSSL: true,
  },
  plugins: ['mup-aws-beanstalk'],
};
```
  
PS: For the second attempt we have issued the certificate ourselves via AWS.

**Comment by zodern** [comment]
It currently only supports certificates from Amazon Certificate Manager that were validated by email. I will fix it tomorrow.

**Comment by raphaelarias** [comment]
@zodern I see. The only reason we've setup ourselves, is because we needed to deploy to a sub domain, and the emails was being sent to the subdomain.

But even before that, the app doesn't run, I believe. I'm trying one more time after I terminated the previous environment.

**Comment by zodern** [comment]
What do the logs show?

**Comment by raphaelarias** [comment]
I'm deploying in a new env, let me see if it goes through.

**Comment by raphaelarias** [comment]
@zodern They show this:

```
=> Configuring Beanstalk Environment
 Created Environment
=> Waiting for Beanstalk Environment to finish launching
=> Configuring scaling
=> Waiting for Beanstalk Environment to finish updating
  Env Event: Updating environment mup-env-educationlink-for-providers's configuration settings.
  Env Event: Environment health has transitioned from Ok to Severe. 100.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on all instances. Initialization completed 57 seconds ago and took 4 minutes. ELB health is failing or not available for all instances.
=> Deploying new version
=> Waiting for Beanstalk Environment to finish updating
  Env Event: Rolling with Additional Batch deployment policy enabled. Launching  a new batch of 1 additional instance(s).
  Env Event: Added instance [i-0a158da26643828c0] to your environment.
  Env Event: Batch 1: 1 EC2 instance(s) [i-0a158da26643828c0] launched. Deploying application version '5'.
  Env Event: Environment health has transitioned from Severe to Degraded. 100.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on 1 out of 2 instances. Application update in progress on 1 instance. 0 out of 2 instances completed (running for 3 minutes). ELB health is failing or not available for 1 out of 2 instances.
  Env Event: Environment health has transitioned from Degraded to Severe. 80.0 % of the requests are failing with HTTP 5xx. ELB processes are not healthy on 1 out of 2 instances. Application update in progress on 1 instance. 0 out of 2 instances completed (running for 4 minutes). ELB health is failing or not available for 1 out of 2 instances.
  Env Event: Deleted log fragments for this environment.
  Env Event: Retrieving logs prior to instance(s) termination. Logs will be available for an hour in the environment management console and at elasticbeanstalk-us-east-1-892415841327/resources/environments/logs/bundle/e-qkczdpj29f.
  Env Event: During an aborted deployment, some instances may have deployed the new application version. To ensure all instances are running the same version, re-deploy the appropriate application version.
  Env Event: Failed to deploy application.
  Env Event: Instance id(s) 'i-0a158da26643828c0' did not pass health check after command execution. Aborting the operation.
  Env Event: [Instance: i-0a158da26643828c0] Successfully finished bundling 18 log(s)
  Env Event: Excess instance(s) terminated.
  Env Event: Terminating excess instance(s): [i-0a158da26643828c0].
```

**Comment by zodern** [comment]
What does `mup logs` and `mup beanstalk status` show?

**Comment by raphaelarias** [comment]
`mup logs`:

```

Node version
v6.11.5
Npm version
3.10.10
=> Starting health check server
=> Starting App

/var/app/current/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^
MongoError: failed to connect to server [cluster0mongodb.net:27017] on first connect [MongoError: connection 5 to cluster0-g5tqi.mongodb.net:27017 timed out]
```

So that's why, the deploy went just fine. The app was starting, but as we have whitelist of IPs, it can't connect to our MongoDB instance.

I have to add the IPs to our white list.

What would be nice, though, if the deploy finish as "Severe", dump the latest app logs. What do you think?

**Comment by raphaelarias** [comment]
We use MongoDB Atlas, with IP Whitelisting. We've setup a VPC peering connection with AWS. Would it be possible to specify the VPC when deploying the app?

We cannot use AWS' default, as the CIDR block conflicts with Atlas, and there is no way to change AWS default VPC settings, as far as I know.

**Comment by raphaelarias** [comment]
How can I help for us to have this? I believe at the end of the day, it would be nice to have some way to pass options directly to the AWS API (?).

The issue #11, I believe, at the end of the day, wants more flexibility too.

**Comment by zodern** [comment]
> I believe at the end of the day, it would be nice to have some way to pass options directly to the AWS API (?).

One option is to support adding/overriding parts of the beanstalk config. Would modifying [these](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html#command-options-general-ec2vpc) work for you?

**Comment by raphaelarias** [comment]
@zodern Yes, would be perfect.

How can I help to get this done?

**Comment by zodern** [comment]
I will implement it within the next couple of days.

**Comment by raphaelarias** [comment]
I was digging the source code to understand how it works and possibly to help. Am I correct to think that the options to pass to AWS API should be added [here](https://github.com/zodern/mup-aws-beanstalk/blob/a804db41040de48d6eb5d4045c0bbca1d1c4c23b/src/command-handlers.js#L170)?

**Comment by zodern** [comment]
The [`desiredEbConfig`](https://github.com/zodern/mup-aws-beanstalk/blob/a804db41040de48d6eb5d4045c0bbca1d1c4c23b/src/command-handlers.js#L338) should be modified to include the custom options. [This](https://github.com/zodern/mup-aws-beanstalk/commit/b3391be43f5ee5f24192637e7c696cd526701fbb) is how I implemented it if you are curious.

I released 0.3.0 today, which has this feature.

**Comment by raphaelarias** [comment]
Awesome!! Thank you!

**Comment by benseitz** [comment]
@zodern 
I have a similar problem, but my logs show:
```
Node version
v6.11.5
Npm version
3.10.10
=> Starting health check server
=> Starting App
/var/app/current/programs/server/node_modules/fibers/future.js:280
                                                throw(ex);
                                                ^

TypeError: Object.getOwnPropertyDescriptors is not a function
    at insert (packages/mongo/collection.js:435:12)
    at Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core.js:232:19)
    at updateVersions (packages/autoupdate.js:125:20)
    at packages/autoupdate.js:189:3
    at Function.time (/var/app/current/programs/server/profile.js:309:28)
    at /var/app/current/programs/server/boot.js:423:13
    at /var/app/current/programs/server/boot.js:464:5
    at Function.run (/var/app/current/programs/server/profile.js:510:12)
    at /var/app/current/programs/server/boot.js:462:11
```

I researched the problem and others could solve it by updating the node version.
I'm running `Meteor 1.6.0.1` which uses node 8 on my local machine. Do I need to downgrade to Meteor 1.4 in order to run it on Elastic Beanstalk?
