### ISSUE TITLE
NPM failing to update, NGINX refusing to connect to upstream client

### ISSUE THREAD

**Issue by tigrente** [zodern/mup-aws-beanstalk#90]
I'm having issues with npm not updating after a deploy, as well as health issues after deployment.  

Trying with the default Meteor app, it deploys fine, including connecting to my Mongo DB
Trying with the '[todo-react-app](https://github.com/meteor/simple-todos-react)', which requires npm packages, fails.

On deployment, the app gives a 502 Bad Gateway error.

The node.js logs show: 

```
> mup-todo10@1.0.0 start /var/app/current
> bash ./start.sh


┌──────────────────────────────────────────────────┐
│             npm update check failed              │
│       Try running with sudo or get access        │
│       to the local update config store via       │
│ sudo chown -R $USER:$(id -gn $USER) /tmp/.config │
└──────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────┐
│             npm update check failed              │
│       Try running with sudo or get access        │
│       to the local update config store via       │
│ sudo chown -R $USER:$(id -gn $USER) /tmp/.config │
└──────────────────────────────────────────────────┘
Node version
v8.15.1
Npm version
6.10.2
=> Starting health check server
=> Starting App
Note: you are using a pure-JavaScript implementation of bcrypt.
While this implementation will work correctly, it is known to be
approximately three times slower than the native implementation.
In order to use the native implementation instead, run

  meteor npm install --save bcrypt

in the root directory of your application.
[HealthCheck] Mon Aug 05 2019 04:37:23 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:23 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:23 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:23 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:23 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:23 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:38 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:38 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:38 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:38 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:38 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
[HealthCheck] Mon Aug 05 2019 04:37:38 GMT+0000 (UTC): Request to app failed Error: connect ECONNREFUSED 127.0.0.1:8081
/var/app/current/programs/server/node_modules/fibers/future.js:313
						throw(ex);
						^

MongoNetworkError: failed to connect to server [domain.com:27017] on first connect [MongoNetworkError: connection 0 to domain.com:27017 timed out]
    at Pool.<anonymous> (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb-core/lib/connection/connection.js:257:10)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:422:8)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mup-todo10@1.0.0 start: `bash ./start.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mup-todo10@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?


```

The NGINX logs show: 
```
2019/08/05 04:37:08 [warn] 4428#0: duplicate MIME type "text/html" in /etc/nginx/conf.d/proxy.conf:66
2019/08/05 04:37:08 [error] 4436#0: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.45.122, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:37:08 [error] 4436#0: *3 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.34.203, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:37:08 [error] 4436#0: *5 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.73.190, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:37:08 [error] 4436#0: *6 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.91.253, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:37:08 [error] 4436#0: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.65.30, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:37:08 [error] 4436#0: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.21.150, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:40:24 [error] 4436#0: *120 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.73.190, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:40:24 [error] 4436#0: *122 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.65.30, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:40:24 [error] 4436#0: *124 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.91.253, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:40:24 [error] 4436#0: *126 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.45.122, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:40:24 [error] 4436#0: *128 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.21.150, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:40:24 [error] 4436#0: *130 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.34.203, server: , request: "GET /aws-health-check-3984729847289743128904723 HTTP/1.1", upstream: "http://127.0.0.1:8039/aws-health-check-3984729847289743128904723", host: "172.31.16.216"
2019/08/05 04:40:37 [error] 4436#0: *132 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.21.150, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "mup-env-todo10.pvpmjensqc.us-east-1.elasticbeanstalk.com"
2019/08/05 04:40:38 [error] 4436#0: *132 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.21.150, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "mup-env-todo10.pvpmjensqc.us-east-1.elasticbeanstalk.com", referrer: "http://mup-env-todo10.pvpmjensqc.us-east-1.elasticbeanstalk.com/"
2019/08/05 04:40:53 [error] 4436#0: *132 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.21.150, server: , request: "GET / HTTP/1.1", upstream: "http://127.0.0.1:8081/", host: "mup-env-todo10.pvpmjensqc.us-east-1.elasticbeanstalk.com"
2019/08/05 04:40:53 [error] 4436#0: *132 connect() failed (111: Connection refused) while connecting to upstream, client: 172.31.21.150, server: , request: "GET /favicon.ico HTTP/1.1", upstream: "http://127.0.0.1:8081/favicon.ico", host: "mup-env-todo10.pvpmjensqc.us-east-1.elasticbeanstalk.com", referrer: "http://mup-env-todo10.pvpmjensqc.us-east-1.elasticbeanstalk.com/"


```

I tried to add a hook to mup.js file to take ownership of the config file, but this didn't work.

```
module.exports = {
    app: {
        // Tells mup that the AWS Beanstalk plugin will manage the app
        type: 'aws-beanstalk',
        name: 'todo10',
        path: '../',
        env: {
            ROOT_URL: ' <redacted>',
            MONGO_URL: '<redacted>'
        },
        auth: {
            id: '<redacted>',
            secret: '<redacted>'
        },
        minInstances: 1,
        maxInstances: 1
    },
    plugins: ['mup-aws-beanstalk'],
    hooks: {
        'pre.meteor.restart': {
            remoteCommand: 'sudo chown -R $USER:$(id -gn $USER) /tmp/.config; sudo chown -R $USER:$(id -gn $USER) ~/.config'
        },
    }
};
```

Is this a bug, or is there something else I should check?

**Comment by tigrente** [comment]
Solution:  I had to add "node-pre-gyp" to my project and then it began working correctly. 
`meteor npm i node-pre-gyp --save`

Also, when the app failed, it would peg the CPU at 100%.  I'm using Atlas.  After I removed the options from my login URL, it stopped being so aggressive at failing.  

Hope this helps someone!

**Comment by vicjune** [comment]
Hi, I have exactly the same errors as you do. I tried your `node-pre-gyp` solution with and without the hook without success.

My `mup.js` looks like this:
```
module.exports = {
  app: {
    type: 'aws-beanstalk',
    name: '<app-name>',
    path: '../',
    buildOptions: {
      serverOnly: true,
      server: 'https://<domain>',
      buildLocation: '<build-path>',
    },
    auth: {
      id: '<aws-id>',
      secret: '<aws-secret>',
    },
    env: {
      ROOT_URL: 'https://<domain>',
      MONGO_URL:
        'mongodb://<mongo-encoded-user>:<mongo-encoded-pwd>@<cluster>.mongodb.net/<db>',
      MAIL_URL:
        'smtp://<mail-encoded-user>:<mail-encoded-pwd>@<host>:<port>',
    },
    sslDomains: ['<domain>'],
    forceSSL: true,
    region: 'eu-west-1',
    instanceType: 't2.micro',
    minInstances: 2,
    maxInstances: 5,
  },
  plugins: ['mup-aws-beanstalk'],
};

```

Would you have any ideas on what went wrong ?
